name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: install_node.js
        run: apt install node.js
      - name: install_npm
        run: npm install

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: install_node.js
        run: apt install node.js
      - name: run npm test
        run: npm test